table 'Measures Table'
	lineageTag: b35907f9-8c5f-4b29-b631-7e82b98330b9

	measure 'Total Spend' =
			
			SUM(
			    global_ads_performance[ad_spend]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b0aada5f-710c-40f8-95f1-3b5806c33b33

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Revenue' =
			
			SUM(
			    global_ads_performance[revenue]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3250d12c-7129-4dba-9f39-dde382445121

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Conversions' =
			
			SUM(
			    global_ads_performance[conversions]
			)
		formatString: #,0
		lineageTag: 76ac75cf-8609-4fd8-9410-2148b44c0315

	measure 'Global ROAS' =
			
			DIVIDE(
			    [Total Revenue],
			    [Total Spend],
			    0
			)
		formatString: 0.00
		lineageTag: 8f33bccd-a012-4e92-bc69-ffd06b72fbe8

	measure 'Total Clicks' =
			
			SUM(
			    global_ads_performance[clicks]
			)
		formatString: 0
		lineageTag: 64ae23cf-7158-4b7b-b47a-464234ddbf0a

	measure 'Total Impressions' =
			
			SUM(
			    global_ads_performance[impressions]
			)
		formatString: 0
		lineageTag: 3f601538-0041-41e4-8cce-907ad0ffddde

	measure 'Global CTR' =
			
			DIVIDE(
			    [Total Clicks],
			    [Total Impressions],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7e9c0dd9-710f-4f8d-908b-b066829f0068

	measure 'Global CPA' =
			
			DIVIDE(
			    [Total Spend],
			    [Total Conversions],
			    0
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 359d2a52-d1d1-4ab0-8951-421772a04605

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Global CPC' =
			
			DIVIDE(
			    [Total Spend],
			    [Total Clicks],
			    0
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 60ce390f-1bd6-4fea-ba3f-cd757b646e36

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

