table 'Measures Table'
	lineageTag: b35907f9-8c5f-4b29-b631-7e82b98330b9

	measure 'Total Spend' =
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        SUM(global_ads_performance[ad_spend]),
			        BLANK() // Esto limpia el eje X para los días que no quieres ver
			    ),
			    // LÓGICA PARA LA TARJETA O TOTALES
			    CALCULATE(
			        SUM(global_ads_performance[ad_spend]),
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b0aada5f-710c-40f8-95f1-3b5806c33b33

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Revenue' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    // Si el día está en el rango, sumamos; si no, BLANK para que el eje X se contraiga
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        SUM(global_ads_performance[revenue]),
			        BLANK() 
			    ),
			    // LÓGICA PARA LA TARJETA (Total acumulado del periodo seleccionado)
			    CALCULATE(
			        SUM(global_ads_performance[revenue]),
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3250d12c-7129-4dba-9f39-dde382445121

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Conversions' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Detectamos el punto en el eje X del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        SUM(global_ads_performance[conversions]),
			        BLANK() 
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        SUM(global_ads_performance[conversions]),
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: #,0
		lineageTag: 76ac75cf-8609-4fd8-9410-2148b44c0315

	measure 'Global ROAS' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del ROAS (Revenue / Spend)
			VAR ROAS_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[revenue]), 
			        SUM(global_ads_performance[ad_spend]), 
			        0
			    )
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        ROAS_Base,
			        BLANK() // Limpia el gráfico fuera del rango
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        ROAS_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: " 0.00""x"""
		lineageTag: 8f33bccd-a012-4e92-bc69-ffd06b72fbe8

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Clicks' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    // Si el día está en el rango, sumamos; si no, BLANK para que el eje X se contraiga
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        SUM(global_ads_performance[clicks]),
			        BLANK() 
			    ),
			    // LÓGICA PARA LA TARJETA (Total acumulado del periodo)
			    CALCULATE(
			        SUM(global_ads_performance[clicks]),
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: #,0
		lineageTag: 64ae23cf-7158-4b7b-b47a-464234ddbf0a

	measure 'Total Impressions' =
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Esta variable detecta si la fecha de la fila actual del gráfico está en el rango
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        SUM(global_ads_performance[impressions]),
			        BLANK() // Al devolver BLANK, Power BI quita el día del gráfico
			    ),
			    // LÓGICA PARA LA TARJETA (Total acumulado)
			    CALCULATE(
			        SUM(global_ads_performance[impressions]),
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
		formatString: #,0
		lineageTag: 3f601538-0041-41e4-8cce-907ad0ffddde

	measure 'Global CTR' =
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del CTR
			VAR CTR_Base = DIVIDE(SUM(global_ads_performance[clicks]), SUM(global_ads_performance[impressions]), 0)
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        CTR_Base,
			        BLANK() // Limpia el gráfico fuera del periodo
			    ),
			    // LÓGICA PARA LA TARJETA (Total acumulado del periodo)
			    CALCULATE(
			        CTR_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7e9c0dd9-710f-4f8d-908b-b066829f0068

	measure 'Global CPA' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del CPA (Spend / Conversions)
			VAR CPA_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[conversions]), 
			        0
			    )
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        CPA_Base,
			        BLANK() // Limpia el gráfico fuera del rango
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        CPA_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 359d2a52-d1d1-4ab0-8951-421772a04605

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Global CPC' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del CPC (Spend / Clicks)
			VAR CPC_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[clicks]), 
			        0
			    )
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        CPC_Base,
			        BLANK() // Limpia el gráfico fuera del rango seleccionado
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        CPC_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 60ce390f-1bd6-4fea-ba3f-cd757b646e36

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Profit' = [Total Revenue] - [Total Spend]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4b163f27-1d07-405b-a62e-54b5fd740ba2

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Global ROI' =
			
			DIVIDE(
			    [Total Profit],
			    [Total Spend],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bf84e3d5-3e65-47a9-b252-21c3a27145c4

	measure AOV = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del AOV (Revenue / Conversions)
			VAR AOV_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[revenue]), 
			        SUM(global_ads_performance[conversions]), 
			        0
			    )
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        AOV_Base,
			        BLANK() // Limpia el gráfico fuera del rango seleccionado
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        AOV_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 798f9183-4986-4fe7-9f48-71e570e10f3e

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Global CPM' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del CPM (Spend / Impressions * 1000)
			VAR CPM_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[impressions]), 
			        0
			    ) * 1000
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        CPM_Base,
			        BLANK() // Garantiza limpieza total del gráfico
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        CPM_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: cd0b1ff0-9d24-4bb6-abbe-10623bd67b54

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Conversion Rate (CVR)' = ```
			
			VAR Dias = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = IF(Dias == 9999, MIN('Dim_Calendar'[Date]), UltimaFechaGlobal - Dias)
			
			// Capturamos la fecha de la fila/punto actual del gráfico
			VAR FechaFila = SELECTEDVALUE('Dim_Calendar'[Date])
			
			// Definimos el cálculo base del CVR (Conversions / Clicks)
			VAR CVR_Base = 
			    DIVIDE(
			        SUM(global_ads_performance[conversions]), 
			        SUM(global_ads_performance[clicks]), 
			        0
			    )
			
			RETURN
			IF(
			    ISFILTERED('Dim_Calendar'[Date]),
			    // LÓGICA PARA EL GRÁFICO (Eje X)
			    IF(
			        FechaFila > FechaInicio && FechaFila <= UltimaFechaGlobal,
			        CVR_Base,
			        BLANK() // Limpia el gráfico fuera del rango seleccionado
			    ),
			    // LÓGICA PARA LA TARJETA (Total del periodo)
			    CALCULATE(
			        CVR_Base,
			        KEEPFILTERS('Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFechaGlobal)
			    )
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 732fde3c-66a6-499b-b122-cd485ab33789

	measure 'Campaings Records' = COUNTROWS(global_ads_performance)
		formatString: #,0
		lineageTag: 49e3aab0-6bdc-4ead-98a6-aaf2c50d8188

	measure 'Titulo de Ultima Fecha' =
			
			"Bienvenido, última actualización: " & FORMAT(MAX(global_ads_performance[date]), "dd/MM/yyyy")
		lineageTag: c2972acb-97d4-402d-bce7-5a263c7c0086

	measure 'Filtro Periodo Dinamico' =
			
			VAR DiasSeleccionados = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			VAR UltimaFecha = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR FechaInicio = UltimaFecha - DiasSeleccionados
			
			VAR FechaActual = MAX('Dim_Calendar'[Date])
			
			RETURN
			IF(
			    FechaActual > FechaInicio && FechaActual <= UltimaFecha,
			    1,
			    0
			)
		formatString: 0
		lineageTag: 2f670433-b8a2-4ca6-92e9-b03b773f0c5e

	measure 'Spend PM' = ```
			
			CALCULATE(
			    [Total Spend], 
			    DATEADD('Dim_Calendar'[Date], 
			    -1, 
			    MONTH
			    )
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6070b843-81ad-4ce0-9bd9-a424bf39881c

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Spend Var %' = ```
			
			DIVIDE(
			    [Total Spend] - [Spend PM], 
			    [Spend PM], 
			    0
			    )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 76103690-4747-4136-ae67-5bf6c52f4257

	measure 'Spend Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Usamos la misma lógica de fecha máxima global que en Total Spend
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			RETURN
			CALCULATE(
			    SUM(global_ads_performance[ad_spend]), // Suma directa para evitar el BLANK() del ISFILTERED
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > (CurrentPeriodStart - DaysSelected) && 
			    'Dim_Calendar'[Date] <= CurrentPeriodStart
			)
			```
		lineageTag: 1c03dcb0-8543-4bd6-a257-ff585747ba62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Spend Var % Dynamic' =
			
			DIVIDE([Total Spend] - [Spend Previous Period], [Spend Previous Period], 0)
		lineageTag: 31d7a35d-2a2d-430b-90dc-c0995a73b8bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Spend Delta Text Dynamic' = ```
			
			VAR Delta = [Total Spend] - [Spend Previous Period]
			VAR DeltaPct = [Spend Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "al total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [Spend Previous Period] ) || [Spend Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    FORMAT ( Delta, "+$#,##0;-$#,##0" ) & " (" &
			    FORMAT ( DeltaPct, "0.0%" ) &
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: d277d536-e1ea-4358-9a4d-d04d315a4895

	measure 'Spend vs Impr Sparkline SVG' = ```
			
			
			// 1. Configuración de Colores
			
			VAR LineColor = "#0288D1"
			
			VAR BarColor = "#B3E5FC"
			
			VAR PointColor = "#01579B"
			
			
			// 2. Parámetros del Lienzo
			
			VAR Width = 150
			
			VAR Height = 50
			
			VAR Padding = 2
			
			
			// 3. Captura de Periodo (Sincronizado con el segmentador)
			
			VAR DiasSeleccionados = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 9999)
			
			VAR UltimaFecha = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			
			VAR FechaInicio = IF(DiasSeleccionados = 9999, MIN(global_ads_performance[date]), UltimaFecha - DiasSeleccionados)
			
			
			// 4. Crear la tabla de tendencia con VALORES DIARIOS
			
			VAR TrendTable =
			
			    FILTER(
			
			        SUMMARIZE(
			
			            ALL('Dim_Calendar'),
			
			            'Dim_Calendar'[Date],
			
			            "DailySpend", SUM(global_ads_performance[ad_spend]),
			
			            "DailyImpr", SUM(global_ads_performance[impressions])
			
			        ),
			
			        'Dim_Calendar'[Date] > FechaInicio && 'Dim_Calendar'[Date] <= UltimaFecha
			
			    )
			
			
			// 5. Máximos para escalado (basado en la tabla de tendencia)
			
			VAR MaxSpend = MAXX(TrendTable, [DailySpend])
			
			VAR MaxImpr = MAXX(TrendTable, [DailyImpr])
			
			VAR XMinDate = MINX(TrendTable, [Date])
			
			VAR XMaxDate = MAXX(TrendTable, [Date])
			
			VAR DateCount = COUNTROWS(TrendTable)
			
			
			// 6. Generar Coordenadas
			
			VAR SparklineTable =
			
			    ADDCOLUMNS(
			
			        TrendTable,
			
			        "X", INT( (Width - (Padding * 2)) * DIVIDE([Date] - XMinDate, XMaxDate - XMinDate) ) + Padding,
			
			        "Y_Line", INT( (Height - (Padding * 2)) * DIVIDE([DailySpend], MaxSpend) ),
			
			        "Y_Bar", INT( (Height - (Padding * 2)) * DIVIDE([DailyImpr], MaxImpr) )
			
			    )
			
			
			// 7. Renderizado de Barras (Impresiones)
			
			VAR BarWidth = DIVIDE(Width, DateCount) * 0.8
			
			VAR Bars =
			
			    CONCATENATEX(
			
			        SparklineTable,
			
			        "<rect x='" & [X] - (BarWidth/2) & "' y='" & Height - [Y_Bar] & "' width='" & BarWidth & "' height='" & [Y_Bar] & "' fill='" & BarColor & "' />"
			
			    )
			
			
			// 8. Renderizado de Línea (Gasto)
			
			VAR LinePoints = CONCATENATEX(SparklineTable, [X] & "," & Height - [Y_Line], " ", [Date])
			
			
			// 9. Punto Final
			
			VAR LastX = MAXX(FILTER(SparklineTable, [Date] = XMaxDate), [X])
			
			VAR LastY = Height - MAXX(FILTER(SparklineTable, [Date] = XMaxDate), [Y_Line])
			
			
			// 10. SVG Final
			
			VAR SVG =
			
			    "data:image/svg+xml;utf8," &
			
			    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 " & Width & " " & Height & "'>" &
			
			        Bars &
			
			        "<polyline fill='none' stroke='" & LineColor & "' stroke-width='2' stroke-linejoin='round' stroke-linecap='round' points='" & LinePoints & "' />" &
			
			        "<circle cx='" & LastX & "' cy='" & LastY & "' r='2' fill='" & PointColor & "' />" &
			
			    "</svg>"
			
			
			RETURN SVG 
			```
		lineageTag: 68374cda-61a3-45c3-a495-8dcc7736ab37
		dataCategory: ImageUrl

	measure 'Impressions Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			RETURN
			CALCULATE(
			    SUM(global_ads_performance[impressions]), // Suma directa para bypass de lógica de gráfico
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > (CurrentPeriodStart - DaysSelected) && 
			    'Dim_Calendar'[Date] <= CurrentPeriodStart
			)
			```
		formatString: 0
		lineageTag: eb40dd09-fa67-4610-96fc-9ee9ed68bf3c

	measure 'Impressions Var % Dynamic' =
			
			DIVIDE([Total Impressions] - [Impressions Previous Period], [Impressions Previous Period], 0)
		lineageTag: 3dfccf89-3dbb-43db-b95e-38bc278257d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impressions Delta Text Dynamic' = ```
			
			VAR Delta = [Total Impressions] - [Impressions Previous Period]
			VAR DeltaPct = [Impressions Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [Impressions Previous Period] ) || [Impressions Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    FORMAT ( Delta, "+#,##0;-#,##0" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: f379e95d-a4db-4fad-9449-68b8dd86a97c

	measure 'Clicks Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			RETURN
			CALCULATE(
			    SUM(global_ads_performance[clicks]), // Suma directa para bypass de lógica de gráfico
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > (CurrentPeriodStart - DaysSelected) && 
			    'Dim_Calendar'[Date] <= CurrentPeriodStart
			)
			```
		formatString: 0
		lineageTag: 6468c3e7-039c-4820-a52d-dafccb97fb77

	measure 'Clicks Var % Dynamic' =
			
			DIVIDE([Total Clicks] - [Clicks Previous Period], [Clicks Previous Period], 0)
		lineageTag: 56500af2-f45b-4023-a220-570cf555637b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Clicks Delta Text Dynamic' = ```
			
			VAR Delta = [Total Clicks]- [Clicks Previous Period]
			VAR DeltaPct = [Clicks Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [Clicks Previous Period] ) || [Clicks Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    FORMAT ( Delta, "+#,##0;-#,##0" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: cc047b27-398c-4977-8593-4137ffca2172

	measure 'CTR Previous Period' = ```
			
			DIVIDE(
			    [Clicks Previous Period], 
			    [Impressions Previous Period], 
			    0
			)
			```
		lineageTag: 7af473a2-9ca9-4323-a3e9-596425b68528

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CTR Var % Dynamic' = ```
			
			DIVIDE(
			    [Global CTR] - [CTR Previous Period], 
			    [CTR Previous Period], 
			    0
			)
			```
		lineageTag: a5c1605f-88db-4000-b64a-e888958d4ef7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CTR Delta Text Dynamic' = ```
			
			VAR Delta = [Global CTR] - [CTR Previous Period]
			VAR DeltaPct = [CTR Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant."
			    )
			
			RETURN
			IF (
			    ISBLANK ( [CTR Previous Period] ) || [CTR Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    FORMAT ( Delta, "+0.00%;-0.00%" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: c6643fab-a139-49e8-897c-9ab1ba96e9e3

	measure 'CPM Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[impressions]), 
			        0
			    ) * 1000,
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		lineageTag: 77fd7ec0-9d0d-4e37-8c52-309d3dd6febf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPM Var % Dynamic' =
			
			DIVIDE([Global CPM] - [CPM Previous Period], [CPM Previous Period], 0)
		lineageTag: 5eb096e8-0352-440a-975c-374ddfe6d0d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPM Delta Text Dynamic' = ```
			
			VAR Delta = [Global CPM] - [CPM Previous Period]
			VAR DeltaPct = [CPM Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [CPM Previous Period] ) || [CPM Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // Usamos $0.00 porque en CPM los centavos son críticos para la decisión
			    FORMAT ( Delta, "+$0.00;-$0.00" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: fc53517a-ebdb-4a6f-aa6f-aac168de4cae

	measure 'CPC Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior con precisión
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[clicks]), 
			        0
			    ),
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		lineageTag: d56d7c98-18d9-4fa2-ae41-349813c5c004

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPC Var % Dynamic' =
			
			DIVIDE([Global CPC]- [CPC Previous Period], [CPC Previous Period], 0)
		lineageTag: 32d51ced-1223-483d-94ef-a81b2a451a31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPC Delta Text Dynamic' = ```
			
			VAR Delta = [Global CPC] - [CPC Previous Period]
			VAR DeltaPct = [CPC Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [CPC Previous Period] ) || [CPC Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // En CPC los centavos ($0.00) son fundamentales para la optimización
			    FORMAT ( Delta, "+$0.00;-$0.00" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: cc46fbf4-2d8d-41c1-a564-5709d7c9cbc5

	measure 'CPA Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[ad_spend]), 
			        SUM(global_ads_performance[conversions]), 
			        0
			    ),
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		lineageTag: 852f21f2-8516-4094-9314-e7704d643b02

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPA Var % Dynamic' =
			
			DIVIDE([Global CPA] - [CPA Previous Period], [CPA Previous Period], 0)
		lineageTag: 8d5dfb61-8435-41b6-94c1-00d750bf500e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CPA Delta Text Dynamic' = ```
			
			VAR Delta = [Global CPA] - [CPA Previous Period]
			VAR DeltaPct = [CPA Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [CPA Previous Period] ) || [CPA Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // En CPA, el formato de moneda con dos decimales es vital ($0.00)
			    FORMAT ( Delta, "+$0.00;-$0.00" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: b9e28fd6-8226-426a-80eb-aac1d166cef0

	measure 'ROAS Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[revenue]), 
			        SUM(global_ads_performance[ad_spend]), 
			        0
			    ),
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		lineageTag: 5d1ccb90-db70-4e50-9875-90a64070cd02

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ROAS Var % Dynamic' =
			
			DIVIDE([Global ROAS] - [ROAS Previous Period], [ROAS Previous Period], 0)
		lineageTag: 0f39ae01-4489-4c87-be01-d2fd280c126e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ROAS Delta Text Dynamic' = ```
			
			VAR Delta = [Global ROAS] - [ROAS Previous Period]
			VAR DeltaPct = [ROAS Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [ROAS Previous Period] ) || [ROAS Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // IMPORTANTE: Aquí NO usamos "$" porque es un ratio
			    FORMAT ( Delta, "+0.00;-0.00" ) & "x (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: 6a91057d-a7fe-4908-b059-c7ad7b27610c

	measure 'CVR Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[conversions]), 
			        SUM(global_ads_performance[clicks]), 
			        0
			    ),
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 5c225eb3-30ff-4029-a6b2-d6cdcad5832e

	measure 'CVR Var % Dynamic' =
			
			DIVIDE([Conversion Rate (CVR)]- [CVR Previous Period], [CVR Previous Period], 0)
		lineageTag: b1fa1bfb-e6c0-4963-9cdf-cfd8b983728e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CVR Delta Text Dynamic' = ```
			
			VAR Delta = [Conversion Rate (CVR)] - [CVR Previous Period]
			VAR DeltaPct = [CVR Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [CVR Previous Period] ) || [CVR Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // Usamos +0.00% porque el CVR se mide en puntos porcentuales
			    FORMAT ( Delta, "+0.00%;-0.00%" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: db54b3a1-582a-4ef3-a16c-dcfb828a8952

	measure 'AOV Previous Period' = ```
			
			VAR DaysSelected = SELECTEDVALUE('Tabla Periodos Dinamicos'[Dias], 30)
			// Sincronizamos con la misma fecha máxima global
			VAR UltimaFechaGlobal = CALCULATE(MAX(global_ads_performance[date]), ALL(global_ads_performance))
			VAR CurrentPeriodStart = UltimaFechaGlobal - DaysSelected
			
			// Definimos el rango del periodo anterior con precisión
			VAR StartDatePrev = CurrentPeriodStart - DaysSelected
			VAR EndDatePrev = CurrentPeriodStart
			
			RETURN
			CALCULATE(
			    DIVIDE(
			        SUM(global_ads_performance[revenue]), 
			        SUM(global_ads_performance[conversions]), 
			        0
			    ),
			    REMOVEFILTERS('Tabla Periodos Dinamicos'),
			    REMOVEFILTERS('Dim_Calendar'),
			    'Dim_Calendar'[Date] > StartDatePrev && 
			    'Dim_Calendar'[Date] <= EndDatePrev
			)
			```
		lineageTag: 84cc0197-61dd-4db4-b7ed-9f06a5cddff3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOV Var % Dynamic' =
			
			DIVIDE([AOV] - [AOV Previous Period], [AOV Previous Period], 0)
		lineageTag: 74e2fe06-724c-4d3a-b0b6-37077e5d2ed7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOV Delta Text Dynamic' = ```
			
			VAR Delta = [AOV] - [AOV Previous Period]
			VAR DeltaPct = [AOV Var % Dynamic]
			VAR PeriodoSeleccionado = SELECTEDVALUE('Tabla Periodos Dinamicos'[Periodo], "Periodo")
			
			// Creamos un sufijo dinámico basado en la selección del usuario
			VAR SufijoDinamico = 
			    SWITCH(
			        PeriodoSeleccionado,
			        "Últimos 7 Días", "7d ant.",
			        "Últimos 14 Días", "14d ant.",
			        "Últimos 28 Días", "28d ant.",
			        "Últimos 30 Días", "30d ant.",
			        "Últimos 90 Días", "90d ant.",
			        "Todo", "total",
			        "per. ant." // Valor por defecto
			    )
			
			RETURN
			IF (
			    ISBLANK ( [AOV Previous Period] ) || [AOV Previous Period] = 0 || PeriodoSeleccionado = "Todo",
			    "Dataset completo",
			    // Para AOV usamos formato de moneda con 2 decimales en el Delta
			    FORMAT ( Delta, "+$#,##0.00;-$#,##0.00" ) & " (" & 
			    FORMAT ( DeltaPct, "0.0%" ) & 
			    IF ( Delta >= 0, " ↑", " ↓" ) & ") vs " & SufijoDinamico
			)
			```
		lineageTag: 09f04b6d-582b-4d14-9b6d-c33897426296

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

